name: edgex-device-onvif-camera
base: core20
license: Apache-2.0
summary: EdgeX ONVIF Camera Device Service
description: Refer to https://snapcraft.io/edgex-device-onvif-camera
adopt-info: device-onvif-camera

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

slots:
  edgex-secretstore-token:
    interface: content
    source:
      write: [$SNAP_DATA/device-onvif-camera]

plugs:
  device-onvif-camera-config:
    interface: content
    target: $SNAP_DATA/config/device-onvif-camera

  # deprecated
  device-config:
    interface: content
    target: $SNAP_DATA/config/device-onvif-camera

apps:
  device-onvif-camera:
    adapter: full
    command: bin/device-onvif-camera --configDir $SNAP_DATA/config/device-onvif-camera/res --configProvider --registry
    command-chain:
      - bin/source-env-file.sh
    environment:
      DEVICE_PROVISIONWATCHERSDIR: $SNAP_DATA/config/device-onvif-camera/res/provisionwatchers
      DEVICE_PROFILESDIR: $SNAP_DATA/config/device-onvif-camera/res/profiles
      DEVICE_DEVICESDIR: $SNAP_DATA/config/device-onvif-camera/res/devices
      SECRETSTORE_TOKENFILE: $SNAP_DATA/device-onvif-camera/secrets-token.json
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind]

parts:
  helper-go:
    source: snap/local/helper-go
    plugin: make
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./helper-go $SNAPCRAFT_PART_INSTALL/bin/helper-go

  device-onvif-camera:
    source: .
    plugin: make
    build-packages: [git]
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi

      # set the version of the snap
      snapcraftctl set-version $VERSION
      
      # write version to file for the build
      echo $VERSION > VERSION

      make build

      install -DT cmd/device-onvif-camera $SNAPCRAFT_PART_INSTALL/bin/device-onvif-camera
      
      RES=$SNAPCRAFT_PART_INSTALL/config/device-onvif-camera/res/
      mkdir -p $RES
      cp    cmd/res/configuration.yaml $RES
      cp -r cmd/res/devices $RES
      cp -r cmd/res/profiles $RES
      cp -r cmd/res/provisionwatchers $RES

      DOC=$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-onvif-camera
      mkdir -p $DOC
      cp Attribution.txt $DOC/Attribution.txt
      cp LICENSE $DOC/LICENSE

  local-bin:
    plugin: dump
    source: snap/local/bin
    organize:
      source-env-file.sh: bin/source-env-file.sh

